### PR TITLE
[#88] Display options

### PR DESCRIPTION
**Pull request by joeljunstrom**
Working display options for asset associations

ping @lexi

### CODE REVIEW

**Comment by lexi** [comment]
Should there always be a "Default" option available in the drop-down so you can go back to having no display options set?

**Comment by lexi** [comment]
Or should I just add it as a display option in settings?

**Comment by joeljunstrom** [comment]
Atm. the "default" is assigned in the template https://github.com/unicefsverige/UNICEF/commit/ece9c80e233900e9e9bd1e35a0b2ee2c1f771f57#L0R9

I thought it to be the easiest way to ensure the rendering won't break. Ie display options is always optional.

**Comment by lexi** [comment]
Would be nice to be able to sort options, not critical right now though.

**Comment by lexi** [comment]
Also, fucking AMAZING that you got it to work!

**Comment by joeljunstrom** [comment]
Implementation was easy once we decided on it =) Cache busting was meh tho =(

**Comment by lexi** [comment]
But there is no way to choose or revert to "default" in admin, so once there is display options and you save an asset_association it will get the first display option in the select.

**Comment by lexi** [comment]
The select list should be:
- No option (default)
- Option 1
- Option 2

**Comment by joeljunstrom** [comment]
Ah I thought I had include blank on that. Might have forgot it. Fixing.

**Comment by joeljunstrom** [comment]
@lexi Added blank option and sorting

**Comment by lexi** [comment]
Cool! Let's merge this too.

**Pull request merged**
